### ISSUE TITLE
Lower the MSRV

### ISSUE THREAD

**Issue by vmx** [ipld/rust-ipld-core#13]
The current version needs a minimum supported Rust version of 1.75 due to the `Links` trait returning an iterator.

As such a recent MSRV shouldn't be a blocker for anyone using this library, but it currently is, (see https://github.com/ipld/rust-ipld-core/pull/11 for more). We should find a way to lower the MSRV.

I currently see two ways (if anyone has others, please post here):

 1. Returning a boxed trait instead of an impl trait. For an implementation see #12.
    - Pro: Also the `Codec` trait would work on lower versions
    - Con:
      - It's a breaking change
      - It uses a dynamic trait 
 2. Introduce a `codec` feature flag, which is enabled but default. Users that don't need the `Codec` trait could just disable that feature and use a lower MSRV.
    - Pro: Non-breaking change (as long as you use the default features)
    - Con:
       - You cannot use the `Codec` trait in Rust < 1.75

**Comment by sugyan** [comment]
If this introduces the `codec` feature flag, it would now require a change to allow libraries such as `serde_ipld_dagcbor` to specify something like `no-codec` feature.

**Comment by Stebalien** [comment]
I'd prefer to keep it as-is or return an associated type (where implementers can choose to box). But... IPLD itself is pretty bleeding edge, so requiring a recent version of rust seems pretty reasonable.

**Comment by vmx** [comment]
> I'd prefer to keep it as-is or return an associated type (where implementers can choose to box).

@Stebalien I hope I understand it correctly that having an associated type would looke like this:

```rust
pub trait Links {
    type LinksError;
    type Iter;
    fn links(bytes: &[u8]) -> Result<Self::Iter, Self::LinksError>;
}
```

Returning a boxed iterator work, but `impl Iteractor` does not:

```console
error[E0658]: `impl Trait` in associated types is unstable
  --> src/codec.rs:37:17
   |
37 |     type Iter = impl Iterator<Item = Cid>;
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information

For more information about this error, try `rustc --explain E0658`.
```

So if you would prefer keeping it as-is, would adding the `codec` feature a possible solution you could at least leave with? The the `serde_ipld_dagcbor` would then also need such a feature. I really want to unblock users of this library and I can see the 1.75 might be too new (although indeed IPLD is bleeding edge).

**Comment by vmx** [comment]
I've pushed https://github.com/ipld/rust-ipld-core/compare/codec-feature-flag to get an idea of what the second proposition looks like. I've also pushed https://github.com/ipld/serde_ipld_dagcbor/tree/codec-feature-flag to see the full chain.

@sugyan patching `ipld-core` and `serde_ipld_dagcbor` with those branches with something like that should work:

```toml
[patch.crates-io]
ipld-core = { git = "https://github.com/ipld/rust-ipld-core", branch = "codec-feature-flag" }
serde_ipld_dagcbor = { git = "https://github.com/ipld/serde_ipld_dagcbor", branch = "codec-feature-flag" }
```

And then setting the `ipld-core` and `serde_ipld_dagcbor` dependencies to `default-features = false, features = ["std"]`.

**Comment by Stebalien** [comment]
> @Stebalien I hope I understand it correctly that having an associated type would looke like this:

Yes, I was suggesting using concrete types for now.

But I would actually prefer a feature flag because that is easier to change in the future.

**Comment by sugyan** [comment]
@vmx Thanks for the quick fix! I tried the change to use that branches in my library as well. It seems to be working well!
https://github.com/sugyan/atrium/pull/148
